branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - breaking: true
          release: major
        - revert: true
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - message: '*'
          release: patch
        - subject: '*'
          release: patch
        - scope: no-release
          release: false
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - '@semantic-release/git'
