# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false
go:
  - "1.17"
env:
  - GO111MODULE=on
script:
  - go test -cover ./...
  - go test -bench ''
  - go vet ./...
  - go install honnef.co/go/tools/cmd/staticcheck@latest
  - staticcheck -go 1.17 ./...
  - go get -v -u -d github.com/fzipp/gocyclo/cmd/gocyclo
  - go run github.com/fzipp/gocyclo/cmd/gocyclo -avg .
notifications:
  email:
    on_success: change
    on_failure: change
